#!/usr/bin/env bash
# Idempotent local-dev bootstrap for the WhiskyFest Contracts app.
# Creates a .env.local with a generated AUTH_SECRET and safe placeholders so the
# Next.js dev server and build can boot. Any real credentials provided through the
# Cloud Agent Secrets panel are injected as process env vars and take precedence
# over these placeholders (Next.js does not override already-set env vars).
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env.local ]; then
  echo "[setup-env] .env.local already exists — leaving it untouched."
  exit 0
fi

echo "[setup-env] Creating .env.local with generated AUTH_SECRET and placeholders."

AUTH_SECRET_VALUE="$(openssl rand -base64 32)"

cat > .env.local <<EOF
# Auto-generated by .cursor/setup-env.sh for local Cloud Agent development.
# Placeholder values let the dev server and build boot. Provide real credentials
# via the Secrets panel; injected env vars override these placeholders.

# --- NextAuth ---
AUTH_SECRET=${AUTH_SECRET_VALUE}
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_DISPLAY_TIMEZONE=America/New_York

# --- Portal hostnames (defaults) ---
NYWE_PORTAL_HOST=nywecontracts.winespectator.com
WHISKYFEST_PORTAL_HOST=wacontracts.whiskyadvocate.com
BIG_SMOKE_PORTAL_HOST=bigsmokecontracts.cigaraficionado.com

# --- Google OAuth (placeholder — real login needs @mshanken.com credentials) ---
GOOGLE_CLIENT_ID=placeholder.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=placeholder-google-client-secret

# --- Supabase (placeholder — real DB access needs project credentials) ---
NEXT_PUBLIC_SUPABASE_URL=https://placeholder.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=placeholder-anon-key
SUPABASE_SERVICE_ROLE_KEY=placeholder-service-role-key
EOF

echo "[setup-env] Done."
