import sgMail from '@sendgrid/mail';
import { formatTimestamp } from '@/lib/datetime';
import type { DailyBubble } from '@/types/db';

const BUBBLE_NOTIFY_EMAIL = 'mcapace@mshanken.com';

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function appBaseUrl(): string {
  const u = process.env['NEXTAUTH_URL']?.trim().replace(/\/$/, '');
  if (u) return u;
  const v = process.env['VERCEL_URL']?.trim();
  if (v) return `https://${v}`;
  return 'http://localhost:3000';
}

function typeLabel(t: string): string {
  if (t === 'fact') return 'FACT';
  if (t === 'joke') return 'JOKE';
  return 'QUOTE';
}

export async function sendBubbleGeneratedEmail(bubble: DailyBubble, removeToken: string): Promise<void> {
  const apiKey = process.env['SENDGRID_API_KEY'];
  const fromAddress = process.env['ACCOUNTING_FROM_EMAIL'] ?? process.env['SENDGRID_FROM_EMAIL'] ?? 'contracts@mshanken.com';
  const fromName = 'WhiskyFest Contracts';

  if (!apiKey) {
    console.warn('[bubble-email] SENDGRID_API_KEY not set — skipping bubble notification email');
    return;
  }

  sgMail.setApiKey(apiKey);
  const base = appBaseUrl();
  const removeUrl = `${base}/admin/bubbles/${bubble.id}/remove?token=${encodeURIComponent(removeToken)}`;
  const generatedAt = formatTimestamp(bubble.generated_at);
  const typeLine = typeLabel(bubble.content_type);

  const text = [
    "Today's bubble (generated by AI):",
    '',
    bubble.content,
    bubble.attribution ? `— ${bubble.attribution}` : '',
    '',
    `Type: ${typeLine}`,
    `Generated at: ${generatedAt}`,
    '',
    `If you want to remove this bubble for all users, open (while signed in as an admin):`,
    removeUrl,
    '',
    'The link is valid for 24 hours. You must be logged in as an admin to confirm removal.',
  ]
    .filter(Boolean)
    .join('\n');

  const html = `
    <div style="font-family: system-ui, -apple-system, sans-serif; color: #1a1a1a; max-width: 640px;">
      <p style="font-size:15px;">Today's bubble (generated by AI):</p>
      <p style="font-size:16px;line-height:1.5;margin:16px 0;"><strong>${escape(bubble.content)}</strong>
      ${bubble.attribution ? `<br/><em style="color:#555;">— ${escape(bubble.attribution)}</em>` : ''}</p>
      <p style="font-size:14px;color:#444;">Type: <strong>${escape(typeLine)}</strong><br/>
      Generated at: ${escape(generatedAt)}</p>
      <p style="margin:20px 0;font-size:14px;">If you want to remove this bubble for all users, click below (admin login required; link expires in 24 hours):</p>
      <p><a href="${escape(removeUrl)}" style="display:inline-block;padding:12px 20px;background:#182d6d;color:#fff;text-decoration:none;border-radius:6px;font-weight:600;">Review / remove bubble</a></p>
      <p style="color:#666;font-size:13px;">— WhiskyFest Contracts</p>
    </div>
  `;

  await sgMail.send({
    from: { email: fromAddress, name: fromName },
    to: BUBBLE_NOTIFY_EMAIL,
    subject: `Today's dashboard bubble — ${typeLine}`,
    text,
    html,
  });
}

export async function sendBubbleGenerationFailedEmail(message: string): Promise<void> {
  const apiKey = process.env['SENDGRID_API_KEY'];
  const fromAddress = process.env['ACCOUNTING_FROM_EMAIL'] ?? process.env['SENDGRID_FROM_EMAIL'] ?? 'contracts@mshanken.com';
  const fromName = 'WhiskyFest Contracts';

  if (!apiKey) {
    console.warn('[bubble-email] SENDGRID_API_KEY not set — cannot send failure notice');
    return;
  }

  sgMail.setApiKey(apiKey);
  const text = `Daily bubble generation failed; no bubble was saved for today.\n\nDetails:\n${message}\n`;
  const html = `<p>Daily bubble generation failed; no bubble was saved for today.</p><pre style="white-space:pre-wrap;font-size:13px;">${escape(message)}</pre>`;

  await sgMail.send({
    from: { email: fromAddress, name: fromName },
    to: BUBBLE_NOTIFY_EMAIL,
    subject: 'WhiskyFest Contracts — daily bubble generation failed',
    text,
    html,
  });
}
